
""" ``config`` module.
"""

ENCODING = 'utf-8'
CONTENT_TYPE = 'text/html; charset=%s' % (ENCODING)

MAX_CONTENT_LENGTH = 4 * 1024 * 1024

ENVIRON_HTTPS = 'HTTPS'
#ENVIRON_HTTPS = 'X-FORWARDED-PROTO'
#ENVIRON_HTTPS = 'SERVER_PORT_SECURE'

ENVIRON_HTTPS_VALUE = 'on'
#ENVIRON_HTTPS_VALUE = 'https'
#ENVIRON_HTTPS_VALUE = '1'

ENVIRON_HOST = 'HTTP_HOST'
#ENVIRON_HOST = 'HTTP_X_FORWARDED_HOST'

ENVIRON_REMOTE_ADDR = 'REMOTE_ADDR'
#ENVIRON_REMOTE_ADDR = 'HTTP_X_FORWARDED_FOR'
